# Generated by Django 3.0.7 on 2020-06-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200626_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Read', 'Read'), ('To_Read', 'To Read'), ('Reading', 'Reading')], default='', max_length=10),
        ),
    ]
