# Generated by Django 3.0.7 on 2020-06-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200626_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Reading', 'Reading'), ('Read', 'Read'), ('To_Read', 'To Read')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='note',
            name='page_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
