# Generated by Django 3.0.7 on 2020-06-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200626_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Reading', 'Reading'), ('To_Read', 'To Read'), ('Read', 'Read')], default='', max_length=10),
        ),
    ]
