# Generated by Django 3.0.7 on 2020-06-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200626_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('To_Read', 'To Read'), ('Read', 'Read'), ('Reading', 'Reading')], default='', max_length=10),
        ),
    ]
