# Generated by Django 3.0.7 on 2020-06-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200626_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Reading', 'Reading'), ('Read', 'Read'), ('To_Read', 'To Read')], default='', max_length=10),
        ),
    ]
